import { z } from "zod";
import { failure, ok } from "@/lib/http";
import { getVideoDurationDefaultSeconds } from "@/lib/generation-defaults";
import { enqueueFrameGeneration, enqueueProjectStartupGeneration } from "@/lib/job-runner";
import { createId, nowIso, reconcileTransitions } from "@/lib/project-ops";
import { mutateCurrentProject } from "@/lib/project-store";

const requestSchema = z.object({
  insertAtIndex: z.number().int().min(0).optional(),
  rows: z.array(
    z.object({
      imagePrompt: z.string(),
      referenceImages: z.array(z.string()).optional(),
      usePreviousFrameAsReference: z.boolean().optional(),
    }),
  ),
});

export async function POST(request: Request) {
  try {
    const body = requestSchema.parse(await request.json());
    const { snapshot, result } = await mutateCurrentProject((manifest) => {
      const timestamp = nowIso();
      const hadExistingFramesBeforeCreate = manifest.frames.length > 0;
      const insertAtIndex = Math.max(0, Math.min(body.insertAtIndex ?? manifest.frames.length, manifest.frames.length));
      const createdFrames = body.rows.map((row, rowIndex) => {
        const frameId = createId("frame");

        return {
          id: frameId,
          position: insertAtIndex + rowIndex,
          imagePrompt: row.imagePrompt,
          referenceImages: row.referenceImages ?? [],
          usePreviousFrameAsReference: row.usePreviousFrameAsReference ?? true,
          generationOverrides: {},
          approvedVersionId: null,
          versions: [],
          createdAt: timestamp,
          updatedAt: timestamp,
        };
      });

      manifest.frames.splice(insertAtIndex, 0, ...createdFrames);
      manifest.frames = manifest.frames.map((frame, index) => ({
        ...frame,
        position: index,
        updatedAt: frame.updatedAt === timestamp ? frame.updatedAt : timestamp,
      }));

      reconcileTransitions(manifest);

      return {
        createdFrameIds: createdFrames.map((frame) => frame.id),
        hadExistingFramesBeforeCreate,
      };
    });

    const { createdFrameIds, hadExistingFramesBeforeCreate } = result;
    const firstCreatedFrameId = createdFrameIds[0] ?? null;
    const firstCreatedFrame = firstCreatedFrameId
      ? snapshot.frames.find((frame) => frame.id === firstCreatedFrameId) ?? null
      : null;
    const autoGeneratedFrameIds = createdFrameIds.filter((frameId) => {
      const frame = snapshot.frames.find((item) => item.id === frameId);
      return frame != null && frame.imagePrompt.trim().length > 0;
    });

    if (firstCreatedFrame?.nextAction !== "generate" || autoGeneratedFrameIds.length === 0) {
      return ok(snapshot);
    }

    if (!hadExistingFramesBeforeCreate) {
      const queuedSnapshot = await enqueueProjectStartupGeneration({
        frameIds: autoGeneratedFrameIds,
        transitionIds: snapshot.transitions.map((transition) => transition.id),
        frameOptions: {
          candidateCount: 1,
          size: "1280x720",
          seedMode: "random",
        },
        transitionOptions: {
          duration: getVideoDurationDefaultSeconds(),
          size: "1280x720",
          fps: 24,
        },
      });

      return ok(queuedSnapshot);
    }

    const queuedSnapshot = await enqueueFrameGeneration(autoGeneratedFrameIds, {
      candidateCount: 1,
      size: "1280x720",
      seedMode: "random",
    });

    return ok(queuedSnapshot);
  } catch (error) {
    return failure(error instanceof Error ? error.message : "Failed to create frames");
  }
}
